version: "3.9"
services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5090:8080
    networks:
      - nettw

  api:
    build: 
      context: UrFU_WorkSpace_API
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 5260:8080
    networks:
      - nettw
      
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "Urfu_WorkSpace"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    networks:
      - nettw
    
volumes:
  habrdb-data:
  pgadmin-data:
  
networks:
  nettw:
    driver: bridge
