version: "3.9"
services:
  webapp:
    build: 
      context: .
      dockerfile: UrFU_WorkSpace/Dockerfile
    ports:
      - 8080:8080
    networks:
      - api_net

  api:
    build: 
      context: .
      dockerfile: UrFU_WorkSpace_API/Dockerfile
    depends_on:
      - postgres
    ports:
      - 5260:8080
    networks:
      - postgres_net
      - api_net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_net
      
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "Urfu_WorkSpace"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    networks:
      - postgres_net
    
volumes:
  habrdb-data:
  pgadmin-data:
  
networks:
  postgres_net:
    driver: bridge
  api_net:
    driver: bridge
