version: "3.9"
services:
  api:
    build:
      context: UrFU_WorkSpace_API
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 5260:8080
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - mynetwork

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "Urfu_WorkSpace"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - habrdb-data:/var/lib/postgresql/data/pgdata
    networks:
      - mynetwork

volumes:
  habrdb-data:
  data-protection-keys:

networks:
  mynetwork:
    driver: bridge
