version: "3.9"
services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5290:5290
    networks:
      - api_net
      - postgres_net

  api:
    build: 
      context: UrFU_WorkSpace_API
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 5260:5260
    networks:
      - postgres_net
      - api_net
      
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "Urfu_WorkSpace"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    networks:
      - postgres_net
      - api_net
    
volumes:
  habrdb-data:
  pgadmin-data:
  
networks:
  postgres_net:
    driver: bridge
  api_net:
    driver: bridge
